name: CI-melodic
on:
  push:
    branches:
      - 'melodic'
  pull_request:
    branches:
      - 'melodic'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: testing}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
